Когда запускал приложение на сервер pythinanywhere:
Приложение не запустилось и выдало ошибку, посмотреть может дело в
этом -->

посмотреть настройки файла settings.py, мы в самом начале устанавливали там значение переменной 
ALLOWED_HOSTS = ['127.0.0.1', '<твоё_имя_пользователя>.pythonanywhere.com']
